/* Generated By:JavaCC: Do not edit this line. CompiladorDPPTreeConstants.java Version 5.0 */
package parser;

public interface CompiladorDPPTreeConstants
{
  public int JJTPROGRAMA = 0;
  public int JJTBLOCO = 1;
  public int JJTDECLARACAOGLOBAL = 2;
  public int JJTVARIAVEISGLOBAIS = 3;
  public int JJTW = 4;
  public int JJTPRINCIPAL = 5;
  public int JJTDECLARACAOLOCAL = 6;
  public int JJTVARIAVEISLOCAIS = 7;
  public int JJTVS = 8;
  public int JJTSENTENCAS = 9;
  public int JJTA = 10;
  public int JJTCOMPARACOES = 11;
  public int JJTVALOR = 12;
  public int JJTEXPRESSAO = 13;
  public int JJTOPERADORES = 14;
  public int JJTOPARITMETICO = 15;
  public int JJTSENTENCAIF = 16;
  public int JJTSENTENCAFOR = 17;
  public int JJTSENTENCADO = 18;
  public int JJTSENTENCAATRIBUICAO = 19;
  public int JJTSENTENCAWRITE = 20;
  public int JJTSENTENCAREAD = 21;


  public String[] jjtNodeName = {
    "Programa",
    "Bloco",
    "DeclaracaoGlobal",
    "VariaveisGlobais",
    "W",
    "Principal",
    "DeclaracaoLocal",
    "VariaveisLocais",
    "VS",
    "Sentencas",
    "A",
    "Comparacoes",
    "Valor",
    "Expressao",
    "Operadores",
    "OpAritmetico",
    "SentencaIf",
    "SentencaFor",
    "SentencaDo",
    "SentencaAtribuicao",
    "SentencaWrite",
    "SentencaRead",
  };
}
/* JavaCC - OriginalChecksum=faa079ed0246d48e894bc982563ccae5 (do not edit this line) */
