/* Generated By:JavaCC: Do not edit this line. CompiladorDPPTreeConstants.java Version 5.0 */
public interface CompiladorDPPTreeConstants
{
  public int JJTCOMPILADORDPP = 0;
  public int JJTPROGRAMA = 1;
  public int JJTVARDECL = 2;
  public int JJTTIPO = 3;
  public int JJTATRIBUICAO = 4;
  public int JJTATRIBUIR = 5;
  public int JJTMDECLARACAO = 6;
  public int JJTLOOP = 7;
  public int JJTEXP = 8;
  public int JJTFATOR = 9;
  public int JJTLISTAEXP = 10;
  public int JJTLISTAEXP2 = 11;
  public int JJTSEQCOMANDOS = 12;
  public int JJTCOMANDO = 13;
  public int JJTEXP_LOGICAS = 14;
  public int JJTFATOR_LOGICO = 15;
  public int JJTFUNC = 16;
  public int JJTLISTAARG = 17;
  public int JJTLISTAARG2 = 18;


  public String[] jjtNodeName = {
    "CompiladorDPP",
    "Programa",
    "VarDecl",
    "Tipo",
    "Atribuicao",
    "Atribuir",
    "Mdeclaracao",
    "Loop",
    "Exp",
    "Fator",
    "ListaExp",
    "ListaExp2",
    "SeqComandos",
    "Comando",
    "Exp_logicas",
    "Fator_logico",
    "Func",
    "ListaArg",
    "ListaArg2",
  };
}
/* JavaCC - OriginalChecksum=89e332ed75b5845208d9319225cec7bc (do not edit this line) */
